
title: 西工大舞蹈机器人救援组 # your title
url: 'https://li837730924.github.io/rescueweb/'
baseurl: '/online-cv' #rescueweb



# Profile information
yourname: Liao  ## put your name
location: Shaanxi Province, China


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
